version: "3.7"

services:

  # Deployment
  docker-registry:
    image: registry
    networks:
      - admin
    volumes:
      - shared-registry:/var/lib/registry

  # Monitoring
  portainer-agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - admin
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  # Monitoring
  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - storage-portainer:/data
    networks:
      - admin
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  admin:
    driver: overlay
    attachable: true

volumes:
  storage-portainer:
  shared-registry:
